### ISSUE TITLE
Shift-Insert key is ignored on OSX

### ISSUE THREAD

**Issue by Michaelangel007** [badvision/jace#5] opened 2016-01-10 20:56 UTC
Plugging in an external keyboard `Shift-Insert` to paste text into Jace doesn't work.

**Comment by badvision** [comment] 2016-01-12 23:01
I had extended key sequences at one point but the lack of... well... any keys on the standard apple keyboard forced me to simplify the keyboard shortcuts.  I can add the shift+ins shortcut for paste again, it shouldn't be a biggie.

**Comment by badvision** [comment] 2016-01-14 05:48
Hmm, no I was wrong and the shift+insert combination was already provided as an alternative.  I traced the init code and it is correctly parsed as shift+insert (and not shift+i+n+s+e+r+t or something silly like that), so I'll have to dig further to figure out why it's not trapping that key combination as expected.

**Comment by badvision** [comment] 2016-01-20 06:13
I've reproduced this issue with two external USB keyboards (both Logitech) and it seems to be a Java bug. https://bugs.openjdk.java.net/browse/JDK-8128519  -- I'm going to close this out, just remember that you can use ctrl+shift+v to paste as well, which is a more mac osx friendly alternative anyway.

**Closed by badvision** 2016-01-20 06:13 UTC
